name: Forum Bonus

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2


      - name: install dependencies
        run: |
          sudo /bin/bash prepare.sh


      - name: run the script
        run: |
          cd src && python3 service.py "${{ secrets.USERS }}"
